export const FGV_PORTUGUESE_GRAMMAR_SUBJECTS = [
  { apiSubject: 'Grau do adjetivo', topic: 'Gramática', subtopic: 'Adjetivos', subsubtopic: 'Grau do adjetivo', expectedCount: 4 },
  { apiSubject: 'Classificação dos verbos quanto à predicação (transitividade)', topic: 'Gramática', subtopic: 'Verbos', subsubtopic: 'Classificação dos verbos quanto à predicação (transitividade)', expectedCount: 1 },
  { apiSubject: 'Elementos estruturais do verbo', topic: 'Gramática', subtopic: 'Verbos', subsubtopic: 'Elementos estruturais do verbo', expectedCount: 1 },
  { apiSubject: 'Formas nominais do verbo', topic: 'Gramática', subtopic: 'Verbos', subsubtopic: 'Formas nominais do verbo', expectedCount: 3 },
  { apiSubject: 'Conversão das vozes do verbo', topic: 'Gramática', subtopic: 'Verbos', subsubtopic: 'Conversão das vozes do verbo', expectedCount: 2 },
  { apiSubject: 'Emprego do pronome demonstrativo', topic: 'Gramática', subtopic: 'Pronomes', subsubtopic: 'Emprego do pronome demonstrativo', expectedCount: 4 },
  { apiSubject: 'Emprego do pronome possessivo', topic: 'Gramática', subtopic: 'Pronomes', subsubtopic: 'Emprego do pronome possessivo', expectedCount: 2 },
  { apiSubject: 'Emprego do pronome relativo', topic: 'Gramática', subtopic: 'Pronomes', subsubtopic: 'Emprego do pronome relativo', expectedCount: 1 },
  { apiSubject: 'Figuras de construção ou de sintaxe', topic: 'Gramática', subtopic: 'Sintaxe', subsubtopic: 'Figuras de construção ou de sintaxe', expectedCount: 1 },
  { apiSubject: 'Ordem dos termos da oração', topic: 'Gramática', subtopic: 'Termos da Oração', subsubtopic: 'Ordem dos termos da oração', expectedCount: 3 },
  { apiSubject: 'A sintaxe do período composto', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'A sintaxe do período composto', expectedCount: 3 },
  { apiSubject: 'Reorganização e reescrita de orações e períodos', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'Reorganização e reescrita de orações e períodos', expectedCount: 21 },
  { apiSubject: 'Orações subordinadas adverbiais causais', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'Orações subordinadas adverbiais causais', expectedCount: 1 },
  { apiSubject: 'Orações subordinadas adverbiais comparativas', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'Orações subordinadas adverbiais comparativas', expectedCount: 1 },
  { apiSubject: 'Orações subordinadas adverbiais concessivas', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'Orações subordinadas adverbiais concessivas', expectedCount: 1 },
  { apiSubject: 'Orações subordinadas adverbiais condicionais', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'Orações subordinadas adverbiais condicionais', expectedCount: 2 },
  { apiSubject: 'Orações subordinadas adverbiais consecutivas', topic: 'Gramática', subtopic: 'Período Composto', subsubtopic: 'Orações subordinadas adverbiais consecutivas', expectedCount: 2 },
  { apiSubject: 'Concordância verbal e nominal (sintaxe de concordância)', topic: 'Gramática', subtopic: 'Concordância', subsubtopic: 'Concordância verbal e nominal (sintaxe de concordância)', expectedCount: 2 },
  { apiSubject: 'Sintaxe de regência', topic: 'Gramática', subtopic: 'Regência', subsubtopic: 'Sintaxe de regência', expectedCount: 4 },
  { apiSubject: 'Ortografia', topic: 'Gramática', subtopic: 'Ortografia e Acentuação', subsubtopic: 'Ortografia', expectedCount: 1 },
  { apiSubject: 'Regras de acentuação', topic: 'Gramática', subtopic: 'Ortografia e Acentuação', subsubtopic: 'Regras de acentuação', expectedCount: 5 },
  { apiSubject: 'Emprego dos sinais de pontuação', topic: 'Gramática', subtopic: 'Pontuação', subsubtopic: 'Emprego dos sinais de pontuação', expectedCount: 12 },
  { apiSubject: 'Casos facultativos de crase', topic: 'Gramática', subtopic: 'Crase', subsubtopic: 'Casos facultativos de crase', expectedCount: 1 },
  { apiSubject: 'Casos em que não há crase', topic: 'Gramática', subtopic: 'Crase', subsubtopic: 'Casos em que não há crase', expectedCount: 2 },
  { apiSubject: 'Emprego do sinal indicativo de crase', topic: 'Gramática', subtopic: 'Crase', subsubtopic: 'Emprego do sinal indicativo de crase', expectedCount: 14 },
  { apiSubject: 'Regras práticas de ocorrência de crase', topic: 'Gramática', subtopic: 'Crase', subsubtopic: 'Regras práticas de ocorrência de crase', expectedCount: 2 },
] as const;
