import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { authMiddleware } from '../../middleware/auth.middleware.js';
import type { StudentProfileController } from './student-profile.controller.js';
import { AppError } from '../../core/errors/app-error.js';
import { isValidBrazilianPhone, isValidCpf } from '../../models/person-data.validation.js';

export const studentProfileBodySchema = z.object({
  fullName: z.string().trim().min(2).max(120).optional(),
  phone: z.string().trim().min(10).max(20).optional(),
  cpf: z.string().trim().min(11).max(14).optional(),
  // Avatars may be hosted URLs or cropped data URLs generated by the UI.
  avatarUrl: z.string().trim().min(1).max(2_000_000).optional(),
}).strict().superRefine((input, context) => {
  if (input.phone && !isValidBrazilianPhone(input.phone)) context.addIssue({ code: 'custom', path: ['phone'], message: 'Telefone inválido.' });
  if (input.cpf && !isValidCpf(input.cpf)) context.addIssue({ code: 'custom', path: ['cpf'], message: 'CPF inválido.' });
});

export async function studentProfileRoutes(
  app: FastifyInstance,
  controller: StudentProfileController,
) {
  app.put('/student/profile', { onRequest: authMiddleware }, async (request, reply) => {
    if (!request.user) throw new AppError({ code: 'UNAUTHENTICATED', statusCode: 401, publicMessage: 'Sessao de usuario obrigatoria.' });

    const body = studentProfileBodySchema.safeParse(request.body ?? {});
    if (!body.success) {
      throw new AppError({ code: 'VALIDATION_ERROR', statusCode: 422, publicMessage: 'Dados de perfil inválidos.', internalDetails: body.error.flatten() });
    }

    const data = await controller.updateProfile(request.user, body.data);
    return reply.send({ data });
  });
}
