import type { FastifyReply, FastifyRequest } from 'fastify';
import { AppError } from '../core/errors/app-error.js';
import { flashcardReviewSchema, questionReviewSchema } from '../models/content-review.model.js';
import { createQuestion, listDocumentsForMonitor, listFlashcardsForMonitor, listQuestionsForMonitor, reviewFlashcard, reviewQuestion } from '../repositories/content-review.repository.js';
type Params = { monitorId?: string; questionId?: string; flashcardId?: string };
const questionSchema = questionReviewSchema.extend({ prompt: questionReviewSchema.shape.text }).strict();
const authError = () => new AppError({ code: 'UNAUTHENTICATED', statusCode: 401, publicMessage: 'Sessão de usuário obrigatória.' });
const validationError = (details: unknown) => new AppError({ code: 'VALIDATION_ERROR', statusCode: 422, publicMessage: 'Dados de entrada inválidos.', internalDetails: details });
export class ContentReviewController {
  async listQuestions(request: FastifyRequest<{ Params: Params }>, reply: FastifyReply) { if (!request.user) throw authError(); try { return reply.send({ data: await listQuestionsForMonitor(request.user.id, request.params.monitorId!) }); } catch (cause) { throw new AppError({ code: 'FAILED_TO_LIST_QUESTIONS', statusCode: 500, publicMessage: 'Não foi possível listar as questões.', cause }); } }
  async listFlashcards(request: FastifyRequest<{ Params: Params }>, reply: FastifyReply) { if (!request.user) throw authError(); try { return reply.send({ data: await listFlashcardsForMonitor(request.user.id, request.params.monitorId!) }); } catch (cause) { throw new AppError({ code: 'FAILED_TO_LIST_FLASHCARDS', statusCode: 500, publicMessage: 'Não foi possível listar os flashcards.', cause }); } }
  async listDocuments(request: FastifyRequest<{ Params: Params }>, reply: FastifyReply) { if (!request.user) throw authError(); try { return reply.send({ data: await listDocumentsForMonitor(request.user.id, request.params.monitorId!) }); } catch (cause) { throw new AppError({ code: 'FAILED_TO_LIST_DOCUMENTS', statusCode: 500, publicMessage: 'Não foi possível listar os documentos.', cause }); } }
  async createQuestion(request: FastifyRequest<{ Params: Params; Body: unknown }>, reply: FastifyReply) { if (!request.user) throw authError(); const monitorId = request.params.monitorId; if (!monitorId) throw new AppError({ code: 'MISSING_MONITOR_ID', statusCode: 422, publicMessage: 'Identificador do monitor é obrigatório.' }); const parsed = questionSchema.safeParse(request.body); if (!parsed.success) throw validationError(parsed.error.flatten()); const text = parsed.data.text ?? parsed.data.prompt; if (!text) throw new AppError({ code: 'TEXT_REQUIRED', statusCode: 422, publicMessage: 'O enunciado da questão é obrigatório.' }); try { return reply.status(201).send({ data: await createQuestion(request.user.id, monitorId, { ...parsed.data, text }) }); } catch (cause) { throw new AppError({ code: 'FAILED_TO_CREATE_QUESTION', statusCode: 500, publicMessage: 'Não foi possível criar a questão.', cause }); } }
  async question(request: FastifyRequest<{ Params: Params; Body: unknown }>, reply: FastifyReply) { if (!request.user) throw authError(); const parsed = questionSchema.safeParse(request.body); if (!parsed.success) throw validationError(parsed.error.flatten()); const questionId = request.params.questionId; if (!questionId) throw new AppError({ code: 'MISSING_QUESTION_ID', statusCode: 422, publicMessage: 'Identificador da questão é obrigatório.' }); try { const result = await reviewQuestion(request.user.id, request.params.monitorId || null, questionId, parsed.data); if (!result) throw new AppError({ code: 'QUESTION_NOT_FOUND', statusCode: 404, publicMessage: 'Questão não encontrada.' }); return reply.send({ data: result }); } catch (cause) { if (cause instanceof AppError) throw cause; throw new AppError({ code: 'FAILED_TO_UPDATE_QUESTION', statusCode: 500, publicMessage: 'Não foi possível atualizar a questão.', cause }); } }
  async flashcard(request: FastifyRequest<{ Params: Params; Body: unknown }>, reply: FastifyReply) { if (!request.user) throw authError(); const parsed = flashcardReviewSchema.strict().safeParse(request.body); if (!parsed.success) throw validationError(parsed.error.flatten()); const flashcardId = request.params.flashcardId; if (!flashcardId) throw new AppError({ code: 'MISSING_FLASHCARD_ID', statusCode: 422, publicMessage: 'Identificador do flashcard é obrigatório.' }); const result = await reviewFlashcard(request.user.id, request.params.monitorId || null, flashcardId, parsed.data); if (!result) throw new AppError({ code: 'FLASHCARD_NOT_FOUND', statusCode: 404, publicMessage: 'Flashcard não encontrado.' }); return reply.send({ data: result }); }
}
