import { env } from './env.js';

export const aiModels = {
  reasoningEffort: env.AI_REASONING_EFFORT,
  questionExtraction: env.QUESTION_EXTRACTION_MODEL || env.OPENROUTER_QUESTION_MODEL,
  chat: env.CHAT_AI_MODEL || env.OPENROUTER_QUESTION_MODEL,
  chatMaxTokens: env.CHAT_AI_MAX_TOKENS,
  chatTemperature: env.CHAT_AI_TEMPERATURE,
  chatTimeoutMs: env.CHAT_AI_TIMEOUT_MS,
  flashcardGeneration: env.FLASHCARD_GENERATION_MODEL,
  flashcardGenerationFallback: env.FLASHCARD_GENERATION_FALLBACK_MODEL,
  questionExtractionMaxTokens: env.QUESTION_EXTRACTION_MAX_TOKENS,
  questionExtractionTemperature: env.QUESTION_EXTRACTION_TEMPERATURE,
  questionSourceReconstruction: env.QUESTION_SOURCE_RECONSTRUCTION_MODEL || env.QUESTION_EXTRACTION_MODEL || env.OPENROUTER_QUESTION_MODEL,
  questionSourceReconstructionMaxTokens: env.QUESTION_SOURCE_RECONSTRUCTION_MAX_TOKENS,
  questionSourceReconstructionTemperature: env.QUESTION_SOURCE_RECONSTRUCTION_TEMPERATURE,
  questionCompletion: env.QUESTION_COMPLETION_MODEL,
  questionCompletionMaxTokens: env.QUESTION_COMPLETION_MAX_TOKENS,
  questionCompletionTemperature: env.QUESTION_COMPLETION_TEMPERATURE,
  questionCategorize: env.QUESTION_CATEGORIZE_MODEL || env.QUESTION_COMPLETION_MODEL,
  questionCategorizeMaxTokens: env.QUESTION_CATEGORIZE_MAX_TOKENS,
  questionCategorizeTemperature: env.QUESTION_CATEGORIZE_TEMPERATURE,
  topicProfile: env.TOPIC_PROFILE_MODEL || 'google/gemini-3.7-flash:batch',
  topicProfileMaxTokens: env.TOPIC_PROFILE_MAX_TOKENS,
  topicProfileTemperature: env.TOPIC_PROFILE_TEMPERATURE,
  questionAlternatives: env.QUESTION_ALTERNATIVES_MODEL || env.QUESTION_COMPLETION_MODEL,
  questionAlternativesMaxTokens: env.QUESTION_ALTERNATIVES_MAX_TOKENS,
  questionAlternativesTemperature: env.QUESTION_ALTERNATIVES_TEMPERATURE,
  questionAnswer: env.QUESTION_ANSWER_MODEL || env.QUESTION_COMPLETION_MODEL,
  questionAnswerMaxTokens: env.QUESTION_ANSWER_MAX_TOKENS,
  questionAnswerTemperature: env.QUESTION_ANSWER_TEMPERATURE,
  questionExplanation: env.QUESTION_EXPLANATION_MODEL || env.QUESTION_COMPLETION_MODEL,
  questionExplanationMaxTokens: env.QUESTION_EXPLANATION_MAX_TOKENS,
  questionExplanationTemperature: env.QUESTION_EXPLANATION_TEMPERATURE,
  questionQualityReview: env.QUESTION_QUALITY_REVIEW_MODEL || env.QUESTION_EXPLANATION_MODEL || env.QUESTION_COMPLETION_MODEL,
  questionQualityReviewMaxTokens: env.QUESTION_QUALITY_REVIEW_MAX_TOKENS,
  questionQualityReviewTemperature: env.QUESTION_QUALITY_REVIEW_TEMPERATURE,
  questionCompletionFallback: env.QUESTION_COMPLETION_FALLBACK_MODEL || null,
  enablePaidStructuredFallback: env.ENABLE_PAID_STRUCTURED_FALLBACK === 'true',
  blockTopicClassificationMaxTokens:
    env.DOCUMENT_BLOCK_TOPIC_CLASSIFICATION_MAX_TOKENS || env.BLOCK_TOPIC_CLASSIFICATION_MAX_TOKENS,
  blockTopicClassificationTemperature: env.DOCUMENT_BLOCK_TOPIC_CLASSIFICATION_TEMPERATURE,
  blockTopicClassificationBatchSize: env.BLOCK_TOPIC_CLASSIFICATION_BATCH_SIZE,
  embeddingBatchSize: env.EMBEDDING_BATCH_SIZE,
  questionCandidateConcurrency: env.QUESTION_CANDIDATE_CONCURRENCY,
  flashcardGenerationConcurrency: env.FLASHCARD_GENERATION_CONCURRENCY,
  documentBlockTopicClassification:
    env.DOCUMENT_BLOCK_TOPIC_CLASSIFICATION_MODEL || env.OPENROUTER_QUESTION_MODEL,
} as const;
