-- The selected OpenRouter model returns 2048-dimensional embeddings.
-- Existing vectors cannot be converted from 1536 to 2048, so they are reset
-- and will be regenerated by the worker.
DROP INDEX IF EXISTS document_chunks_embedding_hnsw_idx;

UPDATE document_chunks
SET embedding = NULL,
    status = 'EMBEDDING_PENDING'::"ChunkStatus"
WHERE embedding IS NOT NULL;

ALTER TABLE document_chunks
  ALTER COLUMN embedding TYPE extensions.vector(2048)
  USING NULL::extensions.vector(2048);

-- HNSW has a 2000-dimension limit for the vector type. The halfvec index
-- supports this 2048-dimensional model while the full vector remains stored.
CREATE INDEX document_chunks_embedding_hnsw_idx
  ON document_chunks
  USING hnsw ((embedding::extensions.halfvec(2048)) extensions.halfvec_cosine_ops)
  WHERE embedding IS NOT NULL;
